create table users (
    age integer,
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    email varchar(255) not null,
    name varchar(255),
    password varchar(255) not null,
    primary key (id)
);

create table authorities (
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    role enum ('ADMIN','COMMON') not null unique,
    primary key (id)
);

create table users_authorities (
    authority_id bigint,
    created_at timestamp(6),
    id bigint generated by default as identity,
    updated_at timestamp(6),
    user_id bigint,
    primary key (id)
);

alter table if exists users_authorities add constraint FKdsfxx5g8x8mnxne1fe0yxhjhq foreign key (authority_id) references authorities;
alter table if exists users_authorities add constraint FKq3lq694rr66e6kpo2h84ad92q foreign key (user_id) references users;

insert into authorities (role) values ('ADMIN');
insert into authorities (role) values ('COMMON');
