spring:

  # DB 연결 정보
  datasource:
    demo:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:demo;MODE=MYSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE # 인메모리 모드 (애플리케이션 종료 시 데이터 삭제)
      #      url: jdbc:h2:file:./domain/demo-domain/local;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE  # 파일 기반 모드 (데이터 영속화)
      username: sa
      password:

  # JPA
  jpa:
    demo:
      show_sql: true      # 쿼리 로그 출력
      generate-ddl: true
      database-platform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          hbm2ddl.auto: none  # DB 초기화 전략
          format_sql: true    # 쿼리 로그 포맷 정렬
          highlight_sql: true # 쿼리 하이라이트
          use_sql_comments: true
          jdbc.batch_size: 100

  flyway:
    enabled: false
    demo:
      enabled: true
      locations: classpath:db/migration
      baseline-on-migrate: true
      baseline-version: 0

# 로그
logging:
  level:
    org.springframework: INFO
    org.hibernate:
      orm.jdbc.bind: TRACE
    org.flywaydb: TRACE