server:
  port: 8080

spring:
  config:
    import:
      - 'classpath:application-demo-domain-local.yml'

  h2:
    console:
      enabled: true     # H2 Console 을 사용할지 여부
      path: /h2-console # H2 Console 의 Path

# JWT
jwt:
  secret-key: "Pa3eDdy6vp7LjCS675xDytQXellcR3D+ucMRywj3bXM="
  access-token-expiration: 3600000 # (ms)
  refresh-token-expiration: 86400000 # (ms)

# Swagger https://springdoc.org/#springdoc-openapi-core-properties
springdoc:
  swagger-ui:
    enabled: true               # Swagger UI 사용여부
    path: /swagger-ui.html      # Swagger UI 접근 경로 <http://localhost:8080/swagger-ui.html>
    tags-sorter: alpha          # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /api-docs

# 로그
logging:
  level:
    org.springframework: INFO
    org.hibernate.orm.jdbc.bind: TRACE